#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

wget https://github.com/iafonov/stacker/tarball/master
tar -zxf master
rm master
mv iafonov-stacker-* stacker
rm stacker/install
cd stacker

echo "** Everything was installed to $DIR/stacker"
echo "** Next step is to run bootstrap script: $ ./bootstrap/ubuntu_1_9_2.sh"
